### PR TITLE
Added MagmaPolred dependency

### PR DESCRIPTION
**Pull request by jvoight**
@SamSchiavone did I do this correctly?

### CODE REVIEW

**Comment by SamSchiavone** [comment]
Hi John, I think so, but Edgar is really the right person to ask. Also, if upon pulling you'd like the submodules to be updated as well, the command is a bit more involved:
```
git pull --recurse-submodules=no && git submodule update --recursive --remote --jobs=10
```
I'm guessing the MagmaPolred code will probably never change, though.

**Comment by edgarcosta** [comment]
one needs to add
```
+../MagmaPolred/spec
```
to your spec.

After this PR is merged you will need to do
```
git submodule init
git submodule update --recursive --remote
```
to download the MagmaPolred.

When cloning one needs to add the option`--recurse-submodules`

**Comment by jvoight** [comment]
OK, updated the spec file, so I merged the PR.  I'm not sure if we need to change the README to provide additional instructions for folks from now on, but I'll test it.

**Comment by jvoight** [comment]
It seems to work!  @edgarcosta, are the commands you indicated only necessary to run on top of an existing repo?

**Comment by edgarcosta** [comment]
correct!

**Pull request merged**
